title: Dhanu Gurung Workshops
title: >-
  Dhanu Gurung
year: 2022
email: budhramgurung@gmail.com
description: >-
  Workshop syllabus conducted by Dhanu Gurung
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://workshop.dhanugurung.com"
image_base_url: /assets/img
thumbnail: thumbnail.jpg
author: BRG
author_url: https://freelancerbrg.com

twitter_username: mentorbrg
github_username:  coolbrg

google_analytics: G-RMJDG09LZT

permalink: /:title

collections:
  html-css:
    output: true
    permalink: /html-css/:title
  docker:
    output: true
    permalink: /docker/:title

contacts:
  facebook:
    url: https://www.facebook.com/mentordhanu
    label: Facebook
    class: bx bxl-facebook
  twitter:
    url: https://twitter.com/mentordhanu/
    label: Twitter
    class: bx bxl-twitter
    username: "@mentordhanu"
  github:
    url: https://github.com/coolbrg/
    label: GitHub
    class: bx bxl-github
  linkedin:
    url: https://www.linkedin.com/in/mentordhanu
    label: LinkdIn
    class: bx bxl-linkedin
  email:
    url: mailto:budhramgurung@gmail.com
    label: Email
    class: bx bx-mail-send
  # youtube:
  #   url: https://www.youtube.com/channel/UC8p8tlnY5fykNYv2vZHvQDg
  #   label: YouTube Channel
  #   class: bx bxl-youtube

# Build settings
markdown: kramdown
