title: Dhanu Sir Workshops
year: 2023
email: dhanusirofficial@gmail.com
description: >-
  Workshops conducted by Dhanu Sir
mainsite: "https://dhanusir.com"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://workshop.dhanusir.com"
image_base_url: /assets/img
thumbnail: thumbnail.jpg
author: Dhanu sir
author_url: https://freelancerbrg.com

twitter_username: dhanumentor
github_username:  dhanusir

google_analytics:

permalink: /:title

collections:
  html-css:
    output: true
    permalink: /html-css/:title
  docker:
    output: true
    permalink: /docker/:title

contacts:
  facebook:
    url: https://www.facebook.com/dhanusir
    label: Facebook
    class: bx bxl-facebook
  twitter:
    url: https://twitter.com/dhanumentor/
    label: Twitter
    class: bx bxl-twitter
    username: "@dhanumentor"
  github:
    url: https://github.com/dhanusir/
    label: GitHub
    class: bx bxl-github
  linkedin:
    url: https://www.linkedin.com/in/dhanusir
    label: LinkdIn
    class: bx bxl-linkedin
  email:
    url: mailto:dhanusirofficial@gmail.com
    label: Email
    class: bx bx-mail-send
  youtube:
    url: https://youtube.com/@dhanusir
    label: YouTube Channel
    class: bx bxl-youtube

# Build settings
markdown: kramdown
